---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  use_vagrant_berkshelf_plugin: true

platforms:
#  - name: ubuntu-12.04
  - name: centos-7.3

suites:
  - name: centos-7.3
    run_list:
      - recipe[yum-mysql-community::mysql57]
      - recipe[ibotta-ops-test]
  - name: default
    run_list:
      - recipe[ibotta-ops-test]
    attributes: {}
