source 'https://rubygems.org'
gem 'berkshelf'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'net-ssh'
gem 'kitchen-verifier-serverspec'
gem 'serverspec'

gem 'buff-extensions', '~> 1.0.0'
gem 'nio4r', '~> 1.2.1'
