name 'ibotta-ops-test'
maintainer 'Tom Miller'
maintainer_email 'miller.thomas.j@gmail.com'
license 'all_rights'
description 'Installs/Configures ibotta-ops-test'
long_description 'Installs/Configures ibotta-ops-test'
version '0.1.0'

depends 'application'
depends 'poise-ruby'
depends 'poise-ruby-build'
depends 'git'
depends 'mysql'
depends 'yum-mysql-community'
